#!/bin/bash

source "$CONFIG_DIR/colors.sh" # Loads all defined colors
source "$CONFIG_DIR/icons.sh" # Loads all defined icons

ITEM_DIR="$CONFIG_DIR/items" # Directory where the items are configured
PLUGIN_DIR="$CONFIG_DIR/plugins" # Directory where all the plugin scripts are stored

FONT="SF Pro" # Needs to have Regular, Bold, Semibold, Heavy and Black variants
PADDINGS=3 # All paddings use this value (icon, label, background)
BAR_HEIGHT=37 # Height of menu bar; On MacOS without notch the menu bar is 25px
TILING_MANAGER="yabai" # yabai or aerospace

# Check for Notch on MacBook
# menu bar is at the top; Apple Menu Bar is 25px
#if [[ $(uname -m) == 'arm64' ]]; then
#   BAR_HEIGHT=39
#fi

if [[ "$TILING_MANAGER" == "aerospace" ]]; then
  AEROSPACE_FOCUSED_MONITOR_NO=$(aerospace list-workspaces --focused)
  AEROSPACE_LIST_OF_WINDOWS_IN_FOCUSED_MONITOR=$(aerospace list-windows --workspace $AEROSPACE_FOCUSED_MONITOR_NO | awk -F'|' '{gsub(/^ *| *$/, "", $2); print $2}')
fi

# Unload the macOS on screen indicator overlay for volume change
launchctl unload -F /System/Library/LaunchAgents/com.apple.OSDUIHelper.plist > /dev/null 2>&1 &

# Setting up the general bar appearance of the bar
bar=(
  height=$BAR_HEIGHT
  color=$BAR_COLOR
  border_width=2
  border_color=$BAR_BORDER_COLOR
  shadow=off
  position=top
  sticky=on
  padding_right=10
  padding_left=10
  y_offset=-3
  margin=-2
  topmost=window
)

sketchybar --bar "${bar[@]}"

# Setting up default values
defaults=(
  updates=when_shown
  icon.font="$FONT:Bold:12.0"
  icon.color=$ICON_COLOR
  icon.padding_left=$PADDINGS
  icon.padding_right=$PADDINGS
  label.font="$FONT:Semibold:11.0"
  label.color=$LABEL_COLOR
  label.padding_left=$PADDINGS
  label.padding_right=$PADDINGS
  label.shadow.drawing=on
  label.shadow.distance=2
  label.shadow.color=0xff000000
  padding_right=$PADDINGS
  padding_left=$PADDINGS
  background.height=26
  background.corner_radius=9
  background.border_width=2
  popup.background.border_width=2
  popup.background.corner_radius=9
  popup.background.border_color=$POPUP_BORDER_COLOR
  popup.background.color=$POPUP_BACKGROUND_COLOR
  popup.blur_radius=20
  popup.background.shadow.drawing=on
  scroll_texts=on
)

sketchybar --default "${defaults[@]}"


# Left
source "$ITEM_DIR/apple.sh"

if [[ "$TILING_MANAGER" == "aerospace" ]]; then
  source "$ITEM_DIR/spaces_aerospace.sh"
  source "$ITEM_DIR/front_app_aerospace.sh"
else
  source "$ITEM_DIR/yabai.sh"
fi

# Right
source "$ITEM_DIR/calendar.sh"
#source "$ITEM_DIR/input_source.sh"
source "$ITEM_DIR/battery.sh"
#source "$ITEM_DIR/brew.sh"
#source "$ITEM_DIR/github.sh"
source "$ITEM_DIR/mic.sh"
source "$ITEM_DIR/volume.sh"
#source "$ITEM_DIR/svim.sh"
#source "$ITEM_DIR/cpu.sh"
#source "$ITEM_DIR/weather.sh"
source "$ITEM_DIR/wifi.sh"
source "$ITEM_DIR/right_bracket.sh"
#source "$ITEM_DIR/spotify.sh"
# source "$ITEM_DIR/media.sh"

sketchybar --hotload on

# Forcing all item scripts to run (never do this outside of sketchybarrc)
sketchybar --update

echo "sketchybar configuation loaded.."

