#!/usr/bin/env bash

# ====== Startup ===============================
# the scripting-addition must be loaded manually if
# you are running yabai on macOS Big Sur. Uncomment
# the following line to have the injection performed
# when the config is executed during startup.
#
# for this to work you must configure sudo such that
# it will be able to run the command without password

sudo yabai --load-sa
yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"



# ====== Variables =============================

gaps_top="4"
gaps_bottom="24"
gaps_left="4"
gaps_right="4"
gaps_inner="4"

normal_border_color="010101"
focused_border_color="808080"
preselect_border_color="2d74da"

# ====== Tiling settings =======================

yabai -m config layout                      bsp

yabai -m config top_padding                 "${gaps_top}"
yabai -m config bottom_padding              "${gaps_bottom}"
yabai -m config left_padding                "${gaps_left}"
yabai -m config right_padding               "${gaps_right}"
yabai -m config window_gap                  "${gaps_inner}"

yabai -m config mouse_follows_focus         off
yabai -m config focus_follows_mouse         on

yabai -m config mouse_modifier              fn
yabai -m config mouse_action1               move
yabai -m config mouse_action2               resize

yabai -m config window_topmost              off
yabai -m config window_opacity              off
yabai -m config window_shadow               float

yabai -m config active_window_opacity       1.0
yabai -m config normal_window_opacity       0.9
yabai -m config split_ratio                 0.5
yabai -m config auto_balance                off

# ====== Border settings =======================

yabai -m config window_border               on
yabai -m config window_border_width         2
yabai -m config active_window_border_color  "0xE0${focused_border_color}"
yabai -m config insert_window_border_color  "0xE0${preselect_border_color}"
yabai -m config normal_window_border_color  "0x00${normal_border_color}"

# ====== List of rules =========================

# Open finder always on top
yabai -m rule --add label="Finderall" app="^Finder$" manage=off grid=6:6:1:1:4:4
yabai -m rule --add label="Finder" app="^Finder$" title="(Co(py|nnect)|Move|Info|Pref|About Finder)" manage=off
yabai -m rule --add label="Safari" app="^Safari$" title="^(General|(Tab|Password|Website|Extension)s|AutoFill|Se(arch|curity)|Privacy|Advance)$" manage=off

# Open Messages app central
yabai -m rule --add label="Messages" app="^Messages$" manage=off grid=6:6:1:1:4:4

	
# Don't manage Preferences
yabai -m rule --add title='Preferences$' manage=off topmost=on grid=4:4:1:1:2:2  
yabai -m rule --add app='^System Preferences$' manage=off grid=4:4:1:1:2:2  

# Other Stuff
yabai -m rule --add label="Activity Monitor" app="^Activity Monitor$" manage=off
yabai -m rule --add label="KeePassXC" app="^KeePassXC$" manage=off
yabai -m rule --add label="Calculator" app="^Calculator$" manage=off
yabai -m rule --add label="Dictionary" app="^Dictionary$" manage=off
yabai -m rule --add label="mpv" app="^mpv$" manage=off
yabai -m rule --add label="The Unarchiver" app="^The Unarchiver$" manage=off
yabai -m rule --add label="Transmission" app="^Transmission$" manage=off
yabai -m rule --add label="Calendar" app="^Calendar$" manage=off grid=6:6:1:1:4:4
yabai -m rule --add label="Spotify" app="^Spotify$" manage=off grid=6:6:1:1:4:4

# Scratchpad
yabai -m rule --add label="Bitwarden" app="^Bitwarden$" manage=off
yabai -m rule --add label="TickTick" app="^TickTick$" manage=off
yabai -m rule --add label="Slack" app="^Slack$" manage=off grid=6:6:1:1:4:4
yabai -m rule --add label="Rocket.Chat" app="^Rocket.Chat$" manage=off grid=6:6:1:1:4:4

# Mail
yabai -m rule --add app="^Mail$" space=6 



# ====== List of signals =========================

# Destroy empty spaces
yabai -m signal --add event='space_changed' action="sh ~/.config/scripts/empty_space2.sh"

